{% set name = "google-cloud-iot" %}
{% set version = "2.0.2" %}
{% set sha256 = "768ccd567b87bf0030f9458d796cc0a846c40825fa2896b77e9cc7a4af30ba2b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip >=18.1
  run:
    - python
    - google-api-core-grpc >=1.14.0,<2.0.0dev
    - grpc-google-iam-v1 >=0.12.3,<0.13.0dev
    - enum34

test:
  imports:
    - grpc
    - google.cloud.iot
    - google.cloud.iot_v1

about:
  home: https://github.com/googleapis/python-iot
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Google Cloud IoT API client library
  description: "Google Cloud IoT API client library is a Google Cloud service that lets client applications communicate with the Google Cloud IoT platform. Google Cloud IoT is a complete set of tools to connect, process, store, and analyze data both at the edge and in the cloud. The platform consists of scalable, fully-managed\
    \ cloud services as well as an integrated software stack for edge/on-premises computing with machine learning capabilities for all your IoT needs.\nSee the [quick start guide](https://googleapis.dev/python/iot/latest/index.html#quick-start)."

  doc_url: https://googleapis.dev/python/iot/latest/index.html
  dev_url: https://github.com/googleapis/python-iot

extra:
  recipe-maintainers:
    - parthea
